# Generated by Django 3.2.5 on 2021-07-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('ic_id', models.CharField(max_length=100, null=True, unique=True)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('ic_pass', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone_no', models.CharField(max_length=100, null=True)),
                ('telephone', models.CharField(max_length=100, null=True)),
                ('highest_degree', models.CharField(max_length=100, null=True)),
                ('school_name', models.CharField(max_length=100, null=True)),
                ('department_school', models.CharField(max_length=100, null=True)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('list_of_test', models.JSONField(default=None, null=True)),
                ('date_joined', models.IntegerField(null=True)),
                ('last_login', models.IntegerField(null=True)),
                ('grade', models.CharField(max_length=5, null=True)),
            ],
            options={
                'ordering': ['last_login'],
            },
        ),
    ]
