# Generated by Django 3.2.5 on 2021-07-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='ic_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
